config/routes.rb
Rails.application.routes.draw do

  resources :sms, only: [:new, :create]

  devise_for :users, :path=>"", :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'register'}

  resources :users, except: :create

  resources :relationships, :only => [:create, :destroy]

  get "dashboard" => 'dashboard#index'
  namespace :dashboard do
  	get "profile"
	  put "update"
    get "users"
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

    shallow do
      resources :leagues do
        resources :divisions do
          resources :teams
        end
        resources :locations
        resources :games
        resources :standings
      end

      resources :conversations do
        resources :messages
      end
    end

  namespace :api, :defaults => {:format => :json} do
    resources :leaguedata
  end

end

app/models/league.rb
class League < ActiveRecord::Base
  has_many :locations
  has_many :games
  has_many :standings
  has_many :divisions
  has_many :teams, through: :divisions

  validates :name, presence: true
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_league, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  # GET /leagues
  # GET /leagues.json
  def index
    @body_class="skin-blue"
    @leagues = League.all
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
    @body_class="skin-blue"
  end

  # GET /leagues/new
  def new
    @body_class="skin-blue"
    @league = League.new
    respond_modal_with @league
  end

  # GET /leagues/1/edit
  def edit
    @body_class="skin-blue"
    respond_modal_with @league
  end

  # POST /leagues
  # POST /leagues.json
  def create
    @league = League.new(league_params)

    respond_to do |format|
      if @league.save
        session[:create_league] = 'League was successfully created.'
        format.html { respond_modal_with @league }
        format.json { render :show, status: :created, location: @league }
      else
        session[:create_errors] = @league.errors.full_messages
        format.html { respond_modal_with @league }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leagues/1
  # PATCH/PUT /leagues/1.json
  def update
    respond_to do |format|
      if @league.update(league_params)
        session[:update_league] = 'League was successfully updated.'
        format.html { respond_modal_with @league }
        format.json { render :show, status: :ok, location: @league }
      else
        session[:update_errors] = @league.errors.full_messages
        format.html { respond_modal_with @league }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    @league.destroy
    respond_to do |format|
      session[:delete_league] = 'League was successfully destroyed.'
      format.html { redirect_to leagues_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def league_params
      params.require(:league).permit(:name, :homeScreen, :rulesScreen)
    end
end

app/views/leagues/_form.html.erb
<section class="content">
  <div class="row">
    <!-- left column -->
    <div class="col-md-12">
      <!-- general form elements -->
      <div class="box box-info">
        <!-- form start -->
        <%= form_for(@league, remote: request.xhr?, html: { data: { modal: true } }) do |f| %>
          
            <div class="box-body">
              <% if session[:create_errors].present? %>
              <div class="alert alert-warning alert-dismissable" style="margin-right: 15px;">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <strong><%=pluralize(session[:create_errors].count, "error")%> prevent from creating</strong><br/>
                  <% session[:create_errors].each do |msg| %>
                    <strong style="color: #FF4400;"><%= msg %></strong><br/>
                  <% end %>
              </div>
            <% end %>
            <% session.delete(:create_errors) %>

            <% if session[:update_errors].present? %>
              <div class="alert alert-warning alert-dismissable" style="margin-right: 15px;">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <strong><%=pluralize(session[:update_errors].count, "error")%> prevent from updating</strong><br/>
                  <% session[:update_errors].each do |msg| %>
                    <strong style="color: #FF4400;"><%= msg %></strong><br/>
                  <% end %>
              </div>
            <% end %>
            <% session.delete(:update_errors) %>

              <div class="form-group">
                <label for="name">Name</label>
                <%= f.text_field :name, :placeholder=>"Enter League name", :class=>"form-control", :disabled=> false %>
              </div>
            </div><!-- /.box-body -->
            <div class="box-footer pull-right">
              <%= f.button :class=>"btn btn-success fa fa-check" %>
              <%= f.button ' Back', :class => "btn btn-primary fa fa-times", "data-dismiss" => "modal" %>
            </div>
        <% end %>

      </div><!-- /.box -->
    </div><!--/.col (left) -->
  </div>   <!-- /.row -->
</section><!-- /.content

app/views/leagues/edit.html.erb
<%= content_for :title, 'Edit league' %>
<%= render 'form' %>

app/views/leagues/index.html.erb
<%= render(:partial=>"dashboard/header") %>
<div class="wrapper row-offcanvas row-offcanvas-left">
<%= render(:partial=>"dashboard/leftside", :locals=>{:active=>'Leagues'}) %>
  <!-- Right side column. Contains the navbar and content of the page -->
  <aside class="right-side">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Leagues
        <small>All leagues</small>
      </h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fa fa-cogs"></i> Leagues</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- top row -->
      <div class="row">
        <div class="col-xs-12 connectedSortable">

          <% if session[:delete_league].present? %>
            <div class="alert alert-success alert-dismissable" style="margin-right: 15px;">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <strong><%= session[:delete_league] %></strong><br/>
            </div>
          <% end %>
          <% session.delete(:delete_league) %>

        </div><!-- /.col -->
      </div>
      <!-- /.row -->
      <!-- Main row -->
      <div class="row">
        <!-- Left col -->
        <section class="col-lg-12 connectedSortable">
          <!-- user info -->
          <div class="box box-info">
            <div class="box-header">
              <i class="fa fa-cogs"></i>
              <h3 class="box-title">Leagues Info</h3>
              <div class="box-tools pull-right">
                <%= link_to 'Add League', new_league_path, data: { modal: true }, class: "btn btn-default" %>
              </div>
            </div>

            <div class="box-body" style="overflow: hidden;">
              <div class="col-sm-12">
                <table class="table table-striped">
                  <tbody>
                    <tr>
                      <th>Name</th>
                      <th colspan="1"></th>
                    </tr>
                    <% @leagues.each do |league| %>
                      <tr>
                        <td>
                          <%= league.name %>
                        </td>
                        <td>
                          <%= link_to ' Show', league, class: "btn btn-info fa fa-eye" %>

                          <%= link_to ' Edit', edit_league_path(league), class: "btn btn-warning fa fa-pencil-square-o", data: { modal: true } %>

                          <%= link_to ' Delete', league, class: "btn btn-danger fa fa-trash-o", method: :delete, data: { confirm: 'Are you sure?' } %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </section><!-- /.Left col -->
      </div><!-- /.row (main row) -->
    </section><!-- /.content -->
  </aside><!-- /.right-side -->
</div><!-- ./wrapper -->

app/views/leagues/new.html.erb
<%= content_for :title, 'New league' %>
<%= render 'form' %>

app/views/leagues/show.html.erb
<%= render(:partial=>"dashboard/header") %>
<div class="wrapper row-offcanvas row-offcanvas-left">
<%= render(:partial=>"dashboard/leftside", :locals=>{:active=>'Leagues'}) %>
  <!-- Right side column. Contains the navbar and content of the page -->
  <aside class="right-side">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        #<%= @league.id %>
        <small><%= @league.name %></small>
      </h1>
      <ol class="breadcrumb">
        <li class="active"><%= @league.name %> </li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- top row -->
      <div class="row">
        <div class="col-xs-12 connectedSortable">

          <% if session[:create_league].present? %>
            <div class="alert alert-success alert-dismissable" style="margin-right: 15px;">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <strong><%= session[:create_league] %></strong><br/>
            </div>
          <% end %>
          <% session.delete(:create_league) %>


          <% if session[:update_league].present? %>
            <div class="alert alert-success alert-dismissable" style="margin-right: 15px;">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <strong><%= session[:update_league] %></strong><br/>
            </div>
          <% end %>
          <% session.delete(:update_league) %>

        </div><!-- /.col -->
      </div>
      <!-- /.row -->
      <!-- Main row -->
      <div class="row">
        <!-- Left col -->
        <section class="col-lg-12 connectedSortable">
          <!-- user info -->
          <div class="box box-info">
            <div class="box-header">
              <i class="fa fa-cogs"></i>
              <h3 class="box-title"><%= @league.name %>'s Info&nbsp&nbsp&nbsp</h3>
              <div class="box-tools">
                <%= link_to 'Back', leagues_path, class: "btn btn-default" %>
              </div>
            </div>

            <div class="box-body" style="overflow: hidden;">
              <div class="col-sm-12">
                <div class="col-md-3 col-sm-6 col-xs-12">

                  <div class="info-box bg-aqua">
                    <span class="info-box-icon"><i class="fa fa-sitemap"></i></span>
                    <div class="info-box-content">
                      <span class="info-box-text">Divisions</span>
                      <span class="info-box-number"><%= @league.divisions.count %></span>
                      <div class="progress">
                        <div class="progress-bar"></div>
                      </div>
                      <span class="progress-description">
                        <%= link_to ' Click to view', league_divisions_path(@league), class: 'fa fa-share', style: 'color: white' %>
                      </span>
                    </div><!-- /.info-box-content -->
                  </div><!-- /.info-box -->
                </div>

                <div class="col-md-3 col-sm-6 col-xs-12">
                  <div class="info-box bg-green">
                    <span class="info-box-icon"><i class="fa fa-gamepad"></i></span>
                    <div class="info-box-content">
                      <span class="info-box-text">Games</span>
                      <span class="info-box-number"><%= @league.games.count %></span>
                      <div class="progress">
                        <div class="progress-bar"></div>
                      </div>
                      <span class="progress-description">
                        <%= link_to ' Click to view', league_games_path(@league), class: 'fa fa-share', style: 'color: white' %>
                      </span>
                    </div><!-- /.info-box-content -->
                  </div><!-- /.info-box -->
                </div>

                <div class="col-md-3 col-sm-6 col-xs-12">
                  <div class="info-box bg-yellow">
                    <span class="info-box-icon"><i class="fa fa-trophy"></i></span>
                    <div class="info-box-content">
                      <span class="info-box-text">Standings</span>
                      <span class="info-box-number"><%= @league.standings.count %></span>
                      <div class="progress">
                        <div class="progress-bar"></div>
                      </div>
                      <span class="progress-description">
                        <%= link_to ' Click to view', league_standings_path(@league), class: 'fa fa-share', style: 'color: white' %>
                      </span>
                    </div><!-- /.info-box-content -->
                  </div><!-- /.info-box -->
                </div>

                <div class="col-md-3 col-sm-6 col-xs-12">
                  <div class="info-box bg-red">
                    <span class="info-box-icon"><i class="fa fa-location-arrow"></i></span>
                    <div class="info-box-content">
                      <span class="info-box-text">Locations</span>
                      <span class="info-box-number"><%= @league.locations.count %></span>
                      <div class="progress">
                        <div class="progress-bar"></div>
                      </div>
                      <span class="progress-description">
                        <%= link_to ' Click to view', league_locations_path(@league), class: 'fa fa-share', style: 'color: white' %>
                      </span>
                    </div><!-- /.info-box-content -->
                  </div><!-- /.info-box -->
                </div>

              </div>
            </div>
          </div>
        </section><!-- /.Left col -->
      </div><!-- /.row (main row) -->
    </section><!-- /.content -->
  </aside><!-- /.right-side -->
</div><!-- ./wrapper -->