config/routes.rb
Rails.application.routes.draw do

  resources :sms, only: [:new, :create]

  devise_for :users, :path=>"", :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'register'}

  resources :users, except: :create

  resources :relationships, :only => [:create, :destroy]

  get "dashboard" => 'dashboard#index'
  namespace :dashboard do
  	get "profile"
	  put "update"
    get "users"
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

    shallow do
      resources :leagues do
        resources :divisions do
          resources :teams
        end
        resources :locations
        resources :games
        resources :standings
      end

      resources :conversations do
        resources :messages
      end
    end

  namespace :api, :defaults => {:format => :json} do
    resources :leaguedata
  end

end

app/models/division.rb
class Division < ActiveRecord::Base
  belongs_to :league
  has_many :teams
  has_many :standings, through: :teams
  
  validates :divisionName, presence: true
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_league, only: [:index, :create, :new]
  before_action :set_division, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  # GET /divisions
  # GET /divisions.json
  def index
    @body_class="skin-blue"
    @divisions = @league.divisions
  end

  # GET /divisions/1
  # GET /divisions/1.json
  def show
    @body_class="skin-blue"
  end

  # GET /divisions/new
  def new
    @body_class="skin-blue"
    @division = Division.new
    respond_modal_with @division
  end

  # GET /divisions/1/edit
  def edit
    @body_class="skin-blue"
    respond_modal_with @division
  end

  # POST /divisions
  # POST /divisions.json
  def create
    @division = @league.divisions.new(division_params)

    respond_to do |format|
      if @division.save
        session[:create_division] = 'Division was successfully created.'
        format.html { respond_modal_with @division }
        format.json { render :show, status: :created, location: @division }
      else
        session[:create_errors] = @division.errors.full_messages
        format.html { respond_modal_with @division }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /divisions/1
  # PATCH/PUT /divisions/1.json
  def update
    respond_to do |format|
      if @division.update(division_params)
        session[:update_division] = 'Division was successfully updated.'
        format.html { respond_modal_with @division }
        format.json { render :show, status: :ok, location: @division }
      else
        session[:update_errors] = @division.errors.full_messages
        format.html { respond_modal_with @division }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /divisions/1
  # DELETE /divisions/1.json
  def destroy
    @division.destroy
    respond_to do |format|
      session[:delete_division] = 'Division was successfully destroyed.'
      format.html { redirect_to league_divisions_path(@division.league) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:league_id])
    end

    def set_division
      @division = Division.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def division_params
      params.require(:division).permit(:divisionName, :league_id)
    end
end

app/views/divisions/_form.html.erb
<!-- Main content -->
<section class="content">
  <div class="row">
    <!-- left column -->
    <div class="col-md-12">
      <!-- general form elements -->
      <div class="box box-info">
        <!-- form start -->
        <%= form_for([@league, @division], remote: request.xhr?, html: { data: { modal: true } }) do |f| %>

            <div class="box-body">

            <% if session[:create_errors].present? %>
              <div class="alert alert-warning alert-dismissable" style="margin-right: 15px;">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <strong><%=pluralize(session[:create_errors].count, "error")%> prevent from creating</strong><br/>
                  <% session[:create_errors].each do |msg| %>
                    <strong style="color: #FF4400;"><%= msg %></strong><br/>
                  <% end %>
              </div>
            <% end %>
            <% session.delete(:create_errors) %>

            <% if session[:update_errors].present? %>
              <div class="alert alert-warning alert-dismissable" style="margin-right: 15px;">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <strong><%=pluralize(session[:update_errors].count, "error")%> prevent from updating</strong><br/>
                  <% session[:update_errors].each do |msg| %>
                    <strong style="color: #FF4400;"><%= msg %></strong><br/>
                  <% end %>
              </div>
            <% end %>
            <% session.delete(:update_errors) %>

              <div class="form-group">
                <label for="name">Name</label>
                <%= f.text_field :divisionName, :placeholder=>"Enter Division name", :class=>"form-control", :disabled=> false %>
              </div>
            </div><!-- /.box-body -->
            <div class="box-footer pull-right">
              <%= f.button :class=>"btn btn-success fa fa-check" %>
              <%= f.button ' Back', :class => "btn btn-primary fa fa-times", "data-dismiss" => "modal" %>
            </div>
        <% end %>

      </div><!-- /.box -->
    </div><!--/.col (left) -->
  </div>   <!-- /.row -->
</section><!-- /.content -->

app/views/divisions/edit.html.erb
<%= content_for :title, 'Edit divison' %>
<%= render 'form' %>

app/views/divisions/index.html.erb
<%= render(:partial=>"dashboard/header") %>
<div class="wrapper row-offcanvas row-offcanvas-left">
<%= render(:partial=>"dashboard/leftside", :locals=>{:active=>'Leagues'}) %>
  <!-- Right side column. Contains the navbar and content of the page -->
  <aside class="right-side">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Divisions
        <small>All Divisions</small>
      </h1>
      <ol class="breadcrumb">
        <li class="active"><%= @league.name %> <i class="fa fa-angle-double-right"></i> Divisions </li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- top row -->
      <div class="row">
        <div class="col-xs-12 connectedSortable">

          <% if session[:delete_division].present? %>
            <div class="alert alert-success alert-dismissable" style="margin-right: 15px;">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <strong><%= session[:delete_division] %></strong><br/>
            </div>
          <% end %>
          <% session.delete(:delete_division) %>

        </div><!-- /.col -->
      </div>
      <!-- /.row -->
      <!-- Main row -->
      <div class="row">
        <!-- Left col -->
        <section class="col-lg-12 connectedSortable">
          <!-- user info -->
          <div class="box box-info">
            <div class="box-header">
              <i class="fa fa-cogs"></i>
              <h3 class="box-title">Divisions Info&nbsp&nbsp&nbsp</h3>
              <div class="box-tools">
                <%= link_to 'Back', league_path(@league), class: "btn btn-default" %>

                <div class="box-tools pull-right">
                  <%= link_to 'Add Division', new_league_division_path, data: { modal: true }, class: "btn btn-default" %>
                </div>
              </div>
            </div>

            <div class="box-body" style="overflow: hidden;">
              <div class="col-sm-12">
                <table class="table table-striped">
                  <tbody>
                    <tr>
                      <th>Name</th>
                      <th colspan="3"></th>
                    </tr>
                    <% @divisions.each do |division| %>
                      <tr>
                        <td>
                          <%= division.divisionName %>
                        </td>
                        <td>
                          <%= link_to ' Show', division, class: "btn btn-info fa fa-eye" %>

                          <%= link_to ' Edit', edit_division_path(division), class: "btn btn-warning fa fa-pencil-square-o", data: { modal: true } %>

                          <%= link_to ' Delete', division, class: "btn btn-danger fa fa-trash-o", method: :delete, data: { confirm: 'Are you sure?' } %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </section><!-- /.Left col -->
      </div><!-- /.row (main row) -->
    </section><!-- /.content -->
  </aside><!-- /.right-side -->
</div><!-- ./wrapper -->

app/views/divisions/new.html.erb
<%= content_for :title, 'New Division' %>
<%= render 'form' %>

app/views/divisions/show.html.erb
<%= render(:partial=>"dashboard/header") %>
<div class="wrapper row-offcanvas row-offcanvas-left">
<%= render(:partial=>"dashboard/leftside", :locals=>{:active=>'Leagues'}) %>
  <!-- Right side column. Contains the navbar and content of the page -->
  <aside class="right-side">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        #<%= @division.id %>
        <small><%= @division.divisionName %></small>
      </h1>
      <ol class="breadcrumb">
        <li class="active"><%= @division.league.name %> <i class="fa fa-angle-double-right"></i> <%= @division.divisionName %> </li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- top row -->
      <div class="row">
        <div class="col-xs-12 connectedSortable">

          <% if session[:create_division].present? %>
            <div class="alert alert-success alert-dismissable" style="margin-right: 15px;">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <strong><%= session[:create_division] %></strong><br/>
            </div>
          <% end %>
          <% session.delete(:create_division) %>


          <% if session[:update_division].present? %>
            <div class="alert alert-success alert-dismissable" style="margin-right: 15px;">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <strong><%= session[:update_division] %></strong><br/>
            </div>
          <% end %>
          <% session.delete(:update_division) %>

        </div><!-- /.col -->
      </div>
      <!-- /.row -->
      <!-- Main row -->
      <div class="row">
        <!-- Left col -->
        <section class="col-lg-12 connectedSortable">
          <!-- user info -->
          <div class="box box-info">
            <div class="box-header">
              <i class="fa fa-cogs"></i>
              <h3 class="box-title"><%= @division.divisionName %>'s Info&nbsp&nbsp&nbsp</h3>
              <div class="box-tools">
                <%= link_to 'Back', :back, class: "btn btn-default" %>
              </div>
            </div>

            <div class="box-body" style="overflow: hidden;">
              <div class="col-sm-12">
                <div class="col-md-3 col-sm-6 col-xs-12">
                  <div class="info-box bg-aqua">
                    <span class="info-box-icon"><i class="fa fa-bookmark-o"></i></span>
                    <div class="info-box-content">
                      <span class="info-box-text">Teams</span>
                      <span class="info-box-number"><%= @division.teams.size %></span>
                      <div class="progress">
                        <div class="progress-bar"></div>
                      </div>
                      <span class="progress-description">
                        <%= link_to ' Click to view', division_teams_path(@division), class: 'fa fa-share', style: 'color: white' %>
                      </span>
                    </div><!-- /.info-box-content -->
                  </div><!-- /.info-box -->
                </div>
              </div>
            </div>
          </div>
        </section><!-- /.Left col -->
      </div><!-- /.row (main row) -->
    </section><!-- /.content -->
  </aside><!-- /.right-side -->
</div><!-- ./wrapper -->