config/routes.rb
Rails.application.routes.draw do

  resources :sms, only: [:new, :create]

  devise_for :users, :path=>"", :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'register'}

  resources :users, except: :create

  resources :relationships, :only => [:create, :destroy]

  get "dashboard" => 'dashboard#index'
  namespace :dashboard do
  	get "profile"
	  put "update"
    get "users"
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

    shallow do
      resources :leagues do
        resources :divisions do
          resources :teams
        end
        resources :locations
        resources :games
        resources :standings
      end

      resources :conversations do
        resources :messages
      end
    end

  namespace :api, :defaults => {:format => :json} do
    resources :leaguedata
  end

end

app/models/standing.rb
class Standing < ActiveRecord::Base
  belongs_to :league
  belongs_to :team
  # has_and_belongs_to_many :divisions
  belongs_to :division

  validates :teamId, :wins, :losses, presence: true

  validates_uniqueness_of :teamId
end

app/controllers/standings_controller.rb
class StandingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_league, only: [:index, :create, :new]
  before_action :set_standing, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  # GET /standings
  # GET /standings.json
  def index
    @body_class="skin-blue"
    @standings = @league.standings
  end

  # GET /standings/1
  # GET /standings/1.json
  def show
    @body_class="skin-blue"
  end

  # GET /standings/new
  def new
    @body_class="skin-blue"
    @standing = Standing.new
    respond_modal_with @standing
  end

  # GET /standings/1/edit
  def edit
    @body_class="skin-blue"
    respond_modal_with @standing
  end

  # POST /standings
  # POST /standings.json
  def create
    #get the team details
    @team = Team.find(standing_params[:teamId])
    teamId = @team.id
    teamName = @team.name
    division = @team.division_id

    #calculation for winning percentage
    @wins = standing_params[:wins]
    @losses = standing_params[:losses]
    winningPct = sprintf "%.3f" % ((@wins.to_f)/((@wins.to_f)+(@losses.to_f)))

    #calculation for pointsDiff
    @pointsFor = (@wins.to_f) * 2
    @pointsAgainst = (@losses.to_f) * 2
    pointsDiff = (@pointsFor.to_i)-(@pointsAgainst.to_i)


    @standing = @league.standings.new(teamId: teamId,
                                      teamName: teamName,
                                      wins: standing_params[:wins],
                                      losses: standing_params[:losses],
                                      winningPct: winningPct,
                                      pointsFor: @pointsFor,
                                      pointsAgainst: @pointsAgainst,
                                      pointsDiff: pointsDiff,
                                      division_id: division,
                                      team_id: teamId)

    respond_to do |format|
      if @standing.save
        session[:create_standing] = 'Standing was successfully created.'
        format.html { respond_modal_with @standing }
        format.json { render :show, status: :created, location: @standing }
      else
        session[:create_errors] = @standing.errors.full_messages
        format.html { respond_modal_with @standing }
        format.json { render json: @standing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /standings/1
  # PATCH/PUT /standings/1.json
  def update

    #calculation for winning percentage
    @wins = standing_params[:wins]
    @losses = standing_params[:losses]
    winningPct = sprintf "%.3f" % ((@wins.to_f)/((@wins.to_f)+(@losses.to_f)))

    #calculation for pointsDiff
    @pointsFor = (@wins.to_f) * 2
    @pointsAgainst = (@losses.to_f) * 2
    pointsDiff = (@pointsFor.to_i)-(@pointsAgainst.to_i)

    respond_to do |format|
      if @standing.update(
                          wins: standing_params[:wins],
                          losses: standing_params[:losses],
                          winningPct: winningPct,
                          pointsFor: @pointsFor,
                          pointsAgainst: @pointsAgainst,
                          pointsDiff: pointsDiff)

        session[:update_standing] = 'Standing was successfully updated.'
        format.html { respond_modal_with @standing }
        format.json { render :show, status: :ok, location: @standing }
      else
        session[:update_errors] = @standing.errors.full_messages
        format.html { respond_modal_with @standing }
        format.json { render json: @standing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /standings/1
  # DELETE /standings/1.json
  def destroy
    @standing.destroy
    respond_to do |format|
      session[:destroy_standing] = 'Standing was successfully destroyed.'
      format.html { redirect_to league_standings_path(@standing.league) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:league_id])
    end

    def set_standing
      @standing = Standing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def standing_params
      params.require(:standing).permit(:teamId, :teamName, :wins, :losses, :winningPct, :pointsFor, :pointsAgainst, :pointsDiff, :league, :division, :team)
    end
end

app/views/standings/_form.html.erb
<!-- Main content -->
<section class="content">
  <div class="row">
    <!-- left column -->
    <div class="col-md-12">
      <!-- general form elements -->
      <div class="box box-info">
        <!-- form start -->
        <%= form_for([@league, @standing], remote: request.xhr?, html: { data: { modal: true } }) do |f| %>

            <div class="box-body">

            <% if session[:create_errors].present? %>
              <div class="alert alert-warning alert-dismissable" style="margin-right: 15px;">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <strong><%=pluralize(session[:create_errors].count, "error")%> prevent from creating</strong><br/>
                  <% session[:create_errors].each do |msg| %>
                    <strong style="color: #FF4400;"><%= msg %></strong><br/>
                  <% end %>
              </div>
            <% end %>
            <% session.delete(:create_errors) %>

            <% if session[:update_errors].present? %>
              <div class="alert alert-warning alert-dismissable" style="margin-right: 15px;">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <strong><%=pluralize(session[:update_errors].count, "error")%> prevent from updating</strong><br/>
                  <% session[:update_errors].each do |msg| %>
                    <strong style="color: #FF4400;"><%= msg %></strong><br/>
                  <% end %>
              </div>
            <% end %>
            <% session.delete(:update_errors) %>
            
              <div class="form-group">
                <label for="team">Team</label>
                <%= f.collection_select :teamId, @league.teams.all, :id, :name, :class=>"form-control" %>
              </div>

              <div class="form-group">
                <label for="wins">Wins</label>
                <%= f.number_field :wins, :class=>"form-control" %>
              </div>

              <div class="form-group">
                <label for="losses">Losses</label>
                <%= f.number_field :losses, :class=>"form-control" %>
              </div>

            </div><!-- /.box-body -->
            <div class="box-footer pull-right">
              <%= f.button :class=>"btn btn-success fa fa-check" %>
              <%= f.button ' Back', :class => "btn btn-primary fa fa-times", "data-dismiss" => "modal" %>
            </div>
        <% end %>
      </div><!-- /.box -->
    </div><!--/.col (left) -->
  </div>   <!-- /.row -->
</section><!-- /.content -->

app/views/standings/_form2.html.erb
<!-- Main content -->
<section class="content">
  <div class="row">
    <!-- left column -->
    <div class="col-md-12">
      <!-- general form elements -->
      <div class="box box-info">
        <!-- form start -->
        <%= form_for([@league, @standing], remote: request.xhr?, html: { data: { modal: true } }) do |f| %>

            <div class="box-body">

            <% if session[:create_errors].present? %>
              <div class="alert alert-warning alert-dismissable" style="margin-right: 15px;">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <strong><%=pluralize(session[:create_errors].count, "error")%> prevent from creating</strong><br/>
                  <% session[:create_errors].each do |msg| %>
                    <strong style="color: #FF4400;"><%= msg %></strong><br/>
                  <% end %>
              </div>
            <% end %>
            <% session.delete(:create_errors) %>

            <% if session[:update_errors].present? %>
              <div class="alert alert-warning alert-dismissable" style="margin-right: 15px;">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <strong><%=pluralize(session[:update_errors].count, "error")%> prevent from updating</strong><br/>
                  <% session[:update_errors].each do |msg| %>
                    <strong style="color: #FF4400;"><%= msg %></strong><br/>
                  <% end %>
              </div>
            <% end %>
            <% session.delete(:update_errors) %>

              <div class="form-group">
                <label for="wins">Wins</label>
                <%= f.number_field :wins, :class=>"form-control" %>
              </div>

              <div class="form-group">
                <label for="losses">Losses</label>
                <%= f.number_field :losses, :class=>"form-control" %>
              </div>

            </div><!-- /.box-body -->
            <div class="box-footer pull-right">
              <%= f.button :class=>"btn btn-success fa fa-check" %>
              <%= f.button ' Back', :class => "btn btn-primary fa fa-times", "data-dismiss" => "modal" %>
            </div>
        <% end %>
      </div><!-- /.box -->
    </div><!--/.col (left) -->
  </div>   <!-- /.row -->
</section><!-- /.content -->

app/views/standings/edit.html.erb
<%= content_for :title, 'Edit Standing' %>
<%= render 'form2' %>

app/views/standings/index.html.erb
<%= render(:partial=>"dashboard/header") %>
<div class="wrapper row-offcanvas row-offcanvas-left">
<%= render(:partial=>"dashboard/leftside", :locals=>{:active=>'Leagues'}) %>
  <!-- Right side column. Contains the navbar and content of the page -->
  <aside class="right-side">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Standings
        <small>All Standings</small>
      </h1>
      <ol class="breadcrumb">
        <li class="active"><%= @league.name %> <i class="fa fa-angle-double-right"></i> Standings </li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- top row -->
      <div class="row">
        <div class="col-xs-12 connectedSortable">

          <% if session[:delete_standing].present? %>
            <div class="alert alert-success alert-dismissable" style="margin-right: 15px;">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <strong><%= session[:delete_standing] %></strong><br/>
            </div>
          <% end %>
          <% session.delete(:delete_standing) %>

        </div><!-- /.col -->
      </div>
      <!-- /.row -->
      <!-- Main row -->
      <div class="row">
        <!-- Left col -->
        <section class="col-lg-12 connectedSortable">
          <!-- user info -->
          <div class="box box-info">
            <div class="box-header">
              <i class="fa fa-cogs"></i>
              <h3 class="box-title">Standings Info&nbsp&nbsp&nbsp</h3>
              <div class="box-tools">
                <%= link_to 'Back', league_path(@league), class: "btn btn-default" %>

                <div class="box-tools pull-right">
                  <%= link_to 'Add Standing', new_league_standing_path, data: { modal: true }, class: "btn btn-default" %>
                </div>
              </div>
            </div>

            <div class="box-body" style="overflow: hidden;">
              <div class="col-sm-12">
                <table class="table table-striped">
                  <tbody>
                    <tr>
                      <th>Team</th>
                      <th>Team name</th>
                      <th>Wins</th>
                      <th>Losses</th>
                      <th>Winningpct</th>
                      <th>Pointsfor</th>
                      <th>Pointsagainst</th>
                      <th>Pointsdiff</th>
                      <th colspan="3"></th>
                    </tr>
                    <% @standings.each do |standing| %>
                      <tr>
                        <td>
                          <%= standing.teamId %>
                        </td>
                        <td>
                          <%= standing.teamName %>
                        </td>
                        <td>
                          <%= standing.wins %>
                        </td>
                        <td>
                          <%= standing.losses %>
                        </td>
                        <td>
                          <%= standing.winningPct %>
                        </td>
                        <td>
                          <%= standing.pointsFor %>
                        </td>
                        <td>
                          <%= standing.pointsAgainst %>
                        </td>
                        <td>
                          <%= standing.pointsDiff %>
                        </td>
                        <td>
                          <%= link_to ' Show', standing, class: "btn btn-info fa fa-eye" %>

                          <%= link_to ' Edit', edit_standing_path(standing), class: "btn btn-warning fa fa-pencil-square-o", data: { modal: true } %>

                          <%= link_to ' Delete', standing, class: "btn btn-danger fa fa-trash-o", method: :delete, data: { confirm: 'Are you sure?' } %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </section><!-- /.Left col -->
      </div><!-- /.row (main row) -->
    </section><!-- /.content -->
  </aside><!-- /.right-side -->
</div><!-- ./wrapper -->

app/views/standings/new.html.erb
<%= content_for :title, 'New Standing' %>
<%= render 'form' %>

app/views/standings/show.html.erb
<%= render(:partial=>"dashboard/header") %>
<div class="wrapper row-offcanvas row-offcanvas-left">
<%= render(:partial=>"dashboard/leftside", :locals=>{:active=>'Leagues'}) %>
  <!-- Right side column. Contains the navbar and content of the page -->
  <aside class="right-side">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        #<%= @standing.id %>
        <small>Standing</small>
      </h1>
      <ol class="breadcrumb">
        <li class="active"><%= @standing.league.name %> <i class="fa fa-angle-double-right"></i> <%= @standing.teamName %> </li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- top row -->
      <div class="row">
        <div class="col-xs-12 connectedSortable">

          <% if session[:create_standing].present? %>
            <div class="alert alert-success alert-dismissable" style="margin-right: 15px;">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <strong><%= session[:create_standing] %></strong><br/>
            </div>
          <% end %>
          <% session.delete(:create_standing) %>


          <% if session[:update_standing].present? %>
            <div class="alert alert-success alert-dismissable" style="margin-right: 15px;">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <strong><%= session[:update_standing] %></strong><br/>
            </div>
          <% end %>
          <% session.delete(:update_standing) %>

        </div><!-- /.col -->
      </div>
      <!-- /.row -->
      <!-- Main row -->
      <div class="row">
        <!-- Left col -->
        <section class="col-lg-12 connectedSortable">
          <!-- user info -->
          <div class="box box-info">
            <div class="box-header">
              <i class="fa fa-cogs"></i>
              <h3 class="box-title">Standing's Info</h3>
            </div>

            <div class="box-body" style="overflow: hidden;">
                <!-- <div class="col-sm-5">
                  <%= image_tag current_user.avatar.url, :class=>'img-responsive' %>
                </div> -->
                <div class="col-sm-7">
                  <table class="table table-striped">
                    <tbody>
                      <tr>
                        <td>Team:</td>
                        <td><%= @standing.teamId %></td>
                      </tr>
                      <tr>
                        <td>Team name:</td>
                        <td><%= @standing.teamName %></td>
                      </tr>
                      <tr>
                        <td>Wins:</td>
                        <td><%= @standing.wins %></td>
                      </tr>
                      <tr>
                        <td>Losses:</td>
                        <td><%= @standing.losses %></td>
                      </tr>
                      <tr>
                        <td>Winningpct:</td>
                        <td><%= @standing.winningPct %></td>
                      </tr>
                      <tr>
                        <td>Pointsfor:</td>
                        <td><%= @standing.pointsFor %></td>
                      </tr>
                      <tr>
                        <td>Pointsagainst:</td>
                        <td><%= @standing.pointsAgainst %></td>
                      </tr>
                      <tr>
                        <td>Pointsdiff:</td>
                        <td><%= @standing.pointsDiff %></td>
                      </tr>
                    </tbody>
                  </table>
                  <br>
                  <br>
                  <%= link_to 'Back', :back, class: 'btn btn-primary fa fa-back' %>
                </div>
            </div>
          </div>
        </section><!-- /.Left col -->
      </div><!-- /.row (main row) -->
    </section><!-- /.content -->
  </aside><!-- /.right-side -->
</div><!-- ./wrapper -->