config/routes.rb
Rails.application.routes.draw do

  resources :sms, only: [:new, :create]

  devise_for :users, :path=>"", :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'register'}

  resources :users, except: :create

  resources :relationships, :only => [:create, :destroy]

  get "dashboard" => 'dashboard#index'
  namespace :dashboard do
  	get "profile"
	  put "update"
    get "users"
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

    shallow do
      resources :leagues do
        resources :divisions do
          resources :teams
        end
        resources :locations
        resources :games
        resources :standings
      end

      resources :conversations do
        resources :messages
      end
    end

  namespace :api, :defaults => {:format => :json} do
    resources :leaguedata
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :league

  validates :location, :team1_id, :team2_id, :time, presence: true
  validates_exclusion_of :team1, in: :team2, message: "and team2 can't be the same"

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_league, only: [:index, :create, :new]
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  # GET /games
  # GET /games.json
  def index
    @body_class="skin-blue"
    @games = @league.games
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @body_class="skin-blue"
  end

  # GET /games/new
  def new
    @body_class="skin-blue"
    @game = Game.new
    respond_modal_with @game
  end

  # GET /games/1/edit
  def edit
    @body_class="skin-blue"
    respond_modal_with @game
  end

  # POST /games
  # POST /games.json
  def create
    #get the location
    @location = Location.find(game_params[:location_id])
    location_id = @location.id
    location = @location.name
    locationUrl = @location.locationUrl

    #get the teams
    @team1_id = Team.find(game_params[:team1_id])
    @team2_id = Team.find(game_params[:team2_id])
    team1_id = @team1_id.id
    team2_id = @team2_id.id
    team1 = @team1_id.name
    team2 = @team2_id.name

    #add new game using all the values above
    @game = @league.games.new(location_id: location_id,
                              location: location,
                              locationUrl: locationUrl,
                              team1_id: team1_id,
                              team1: team1,
                              team2: team2,
                              team2_id: team2_id,
                              team1Score: game_params[:team1Score],
                              team2Score: game_params[:team2Score],
                              time: game_params[:time])

    respond_to do |format|
      if @game.save
        session[:create_game] = 'Game was successfully created.'
        format.html { respond_modal_with @game }
        format.json { render :show, status: :created, location: @game }
      else
        session[:create_errors] = @game.errors.full_messages
        format.html { respond_modal_with @game }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        session[:update_game] = 'Game was successfully updated.'
        format.html { respond_modal_with @game }
        format.json { render :show, status: :ok, location: @game }
      else
        session[:update_errors] = @game.errors.full_messages
        format.html { respond_modal_with @game }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      session[:delete_team] = 'Game was successfully destroyed.'
      format.html { redirect_to league_games_path(@game.league) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:league_id])
    end

    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:locationUrl, :location, :location_id, :team1, :team1_id, :team2, :team2_id, :team1Score, :team2Score, :time, :league_id)
    end
end

app/views/games/_form.html.erb
<!-- Main content -->
<section class="content">
  <div class="row">
    <!-- left column -->
    <div class="col-md-12">
      <!-- general form elements -->
      <div class="box box-info">
        <!-- form start -->
        <%= form_for([@league, @game], remote: request.xhr?, html: { data: { modal: true } }) do |f| %>

            <div class="box-body">

            <% if session[:create_errors].present? %>
              <div class="alert alert-warning alert-dismissable" style="margin-right: 15px;">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <strong><%=pluralize(session[:create_errors].count, "error")%> prevent from creating</strong><br/>
                  <% session[:create_errors].each do |msg| %>
                    <strong style="color: #FF4400;"><%= msg %></strong><br/>
                  <% end %>
              </div>
            <% end %>
            <% session.delete(:create_errors) %>

            <% if session[:update_errors].present? %>
              <div class="alert alert-warning alert-dismissable" style="margin-right: 15px;">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <strong><%=pluralize(session[:update_errors].count, "error")%> prevent from updating</strong><br/>
                  <% session[:update_errors].each do |msg| %>
                    <strong style="color: #FF4400;"><%= msg %></strong><br/>
                  <% end %>
              </div>
            <% end %>
            <% session.delete(:update_errors) %>
            
              <div class="form-group">
                <label for="location">Location</label>
                <%= f.collection_select :location_id, @league.locations, :id, :name, :class=>"form-control" %>
              </div>

              <div class="form-group">
                <label for="name">Team 1</label>
                <%= f.collection_select :team1_id, @league.teams, :id, :name, :class=>"form-control" %>
              </div>

              <div class="form-group">
                <label for="name">Team 2</label>
                <%= f.collection_select :team2_id, @league.teams, :id, :name, :class=>"form-control" %>
              </div>

              <div class="form-group">
                <label for="name">Team 1 Score</label>
                <%= f.number_field :team1Score, :class=>"form-control" %>
              </div>

              <div class="form-group">
                <label for="name">Team 2 Score</label>
                <%= f.number_field :team2Score, :class=>"form-control" %>
              </div>

              <div class="form-group">
                <label for="name">Time</label>
                <%= f.datetime_local_field :time, :class=>"form-control" %>
              </div>


            </div><!-- /.box-body -->
            <div class="box-footer pull-right">
              <%= f.button :class=>"btn btn-success fa fa-check" %>
              <%= f.button ' Back', :class => "btn btn-primary fa fa-times", "data-dismiss" => "modal" %>
            </div>
        <% end %>

      </div><!-- /.box -->
    </div><!--/.col (left) -->
  </div>   <!-- /.row -->
</section><!-- /.content -->

app/views/games/_form2.html.erb
<!-- Main content -->
<section class="content">
  <div class="row">
    <!-- left column -->
    <div class="col-md-12">
      <!-- general form elements -->
      <div class="box box-info">
        <!-- form start -->
        <%= form_for([@league, @game], remote: request.xhr?, html: { data: { modal: true } }) do |f| %>

            <div class="box-body">

            <% if session[:create_errors].present? %>
              <div class="alert alert-warning alert-dismissable" style="margin-right: 15px;">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <strong><%=pluralize(session[:create_errors].count, "error")%> prevent from creating</strong><br/>
                  <% session[:create_errors].each do |msg| %>
                    <strong style="color: #FF4400;"><%= msg %></strong><br/>
                  <% end %>
              </div>
            <% end %>
            <% session.delete(:create_errors) %>

            <% if session[:update_errors].present? %>
              <div class="alert alert-warning alert-dismissable" style="margin-right: 15px;">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <strong><%=pluralize(session[:update_errors].count, "error")%> prevent from updating</strong><br/>
                  <% session[:update_errors].each do |msg| %>
                    <strong style="color: #FF4400;"><%= msg %></strong><br/>
                  <% end %>
              </div>
            <% end %>
            <% session.delete(:update_errors) %>

              <div class="form-group">
                <label for="name">Team 1 Score</label>
                <%= f.number_field :team1Score, :class=>"form-control" %>
              </div>

              <div class="form-group">
                <label for="name">Team 2 Score</label>
                <%= f.number_field :team2Score, :class=>"form-control" %>
              </div>

              <div class="form-group">
                <label for="name">Time</label>
                <%= f.datetime_local_field :time, :class=>"form-control" %>
              </div>


            </div><!-- /.box-body -->
            <div class="box-footer pull-right">
              <%= f.button :class=>"btn btn-success fa fa-check" %>
              <%= f.button ' Back', :class => "btn btn-primary fa fa-times", "data-dismiss" => "modal" %>
            </div>
        <% end %>

      </div><!-- /.box -->
    </div><!--/.col (left) -->
  </div>   <!-- /.row -->
</section><!-- /.content -->

app/views/games/edit.html.erb
<%= content_for :title, 'Edit Game' %>
<%= render 'form2' %>

app/views/games/index.html.erb
<%= render(:partial=>"dashboard/header") %>
<div class="wrapper row-offcanvas row-offcanvas-left">
<%= render(:partial=>"dashboard/leftside", :locals=>{:active=>'Leagues'}) %>
  <!-- Right side column. Contains the navbar and content of the page -->
  <aside class="right-side">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Games
        <small>All Games</small>
      </h1>
      <ol class="breadcrumb">
        <li class="active"><%= @league.name %> <i class="fa fa-angle-double-right"></i> Games</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- top row -->
      <div class="row">
        <div class="col-xs-12 connectedSortable">

          <% if session[:delete_game].present? %>
            <div class="alert alert-success alert-dismissable" style="margin-right: 15px;">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <strong><%= session[:delete_game] %></strong><br/>
            </div>
          <% end %>
          <% session.delete(:delete_game) %>

        </div><!-- /.col -->
      </div>
      <!-- /.row -->
      <!-- Main row -->
      <div class="row">
        <!-- Left col -->
        <section class="col-lg-12 connectedSortable">
          <!-- user info -->
          <div class="box box-info">
            <div class="box-header">
              <i class="fa fa-cogs"></i>
              <h3 class="box-title"> Games Info&nbsp&nbsp&nbsp</h3>
              <div class="box-tools">
                <%= link_to 'Back', league_path(@league), class: "btn btn-default" %>

                <div class="box-tools pull-right">
                  <%= link_to 'Add Game', new_league_game_path, data: { modal: true }, class: "btn btn-default" %>
                </div>
              </div>
            </div>

            <div class="box-body" style="overflow: hidden;">
              <div class="col-sm-12">
                <table class="table table-striped">
                  <tbody>
                    <tr>
                      <th>Location</th>
                      <th>Team 1</th>
                      <th>Team 2</th>
                      <th>Team 1 score</th>
                      <th>Team 2 score</th>
                      <th>Time</th>
                      <th colspan="3"></th>
                    </tr>
                    <% @games.each do |game| %>
                      <tr>
                        <td>
                          <%= game.location %>
                        </td>
                        <td>
                          <%= game.team1 %>
                        </td>
                        <td>
                          <%= game.team2 %>
                        </td>
                        <td>
                          <% unless game.team1Score.nil? %>
                            <%= game.team1Score %>
                          <% else %>
                            <p style="color:red">Upcoming match</p>
                          <% end %>
                        </td>
                        <td>
                          <% unless game.team2Score.nil? %>
                            <%= game.team2Score %>
                          <% else %>
                            <p style="color:red">Upcoming match</p>
                          <% end %>
                        </td>
                        <td>
                            <%= game.time %>
                        </td>
                        <td>
                          <%= link_to ' Show', game, class: "btn btn-info fa fa-eye" %>

                          <%= link_to ' Edit', edit_game_path(game), class: "btn btn-warning fa fa-pencil-square-o", data: { modal: true } %>

                          <%= link_to ' Delete', game, class: "btn btn-danger fa fa-trash-o", method: :delete, data: { confirm: 'Are you sure?' } %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </section><!-- /.Left col -->
      </div><!-- /.row (main row) -->
    </section><!-- /.content -->
  </aside><!-- /.right-side -->
</div><!-- ./wrapper -->

app/views/games/new.html.erb
<%= content_for :title, 'New Game' %>
<%= render 'form' %>

app/views/games/show.html.erb
<%= render(:partial=>"dashboard/header") %>
<div class="wrapper row-offcanvas row-offcanvas-left">
<%= render(:partial=>"dashboard/leftside", :locals=>{:active=>'Leagues'}) %>
  <!-- Right side column. Contains the navbar and content of the page -->
  <aside class="right-side">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        #<%= @game.id %>
        <small>Game</small>
      </h1>
      <ol class="breadcrumb">
        <li class="active"><%= @game.league.name %> <i class="fa fa-angle-double-right"></i> <%= @game.team1 %> VS <%= @game.team2 %> </li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- top row -->
      <div class="row">
        <div class="col-xs-12 connectedSortable">

          <% if session[:create_game].present? %>
            <div class="alert alert-success alert-dismissable" style="margin-right: 15px;">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <strong><%= session[:create_game] %></strong><br/>
            </div>
          <% end %>
          <% session.delete(:create_game) %>


          <% if session[:update_game].present? %>
            <div class="alert alert-success alert-dismissable" style="margin-right: 15px;">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <strong><%= session[:update_game] %></strong><br/>
            </div>
          <% end %>
          <% session.delete(:update_game) %>

        </div><!-- /.col -->
      </div>
      <!-- /.row -->
      <!-- Main row -->
      <div class="row">
        <!-- Left col -->
        <section class="col-lg-12 connectedSortable">
          <!-- user info -->
          <div class="box box-info">
            <div class="box-header">
              <i class="fa fa-cogs"></i>
              <h3 class="box-title">Game's Info</h3>
            </div>

            <div class="box-body" style="overflow: hidden;">
                <!-- <div class="col-sm-5">
                  <%= image_tag current_user.avatar.url, :class=>'img-responsive' %>
                </div> -->
                <div class="col-sm-7">
                  <table class="table table-striped">
                    <tbody>
                      <tr>
                        <td>Location:</td>
                        <td><%= @game.location %></td>
                      </tr>
                      <tr>
                        <td>Team 1:</td>
                        <td><%= @game.team1 %></td>
                      </tr>
                      <tr>
                        <td>Team 2:</td>
                        <td><%= @game.team2 %></td>
                      </tr>
                      <tr>
                        <td>Team 1 score:</td>
                        <td><%= @game.team1Score %></td>
                      </tr>
                      <tr>
                        <td>Team 2 score:</td>
                        <td><%= @game.team2Score %></td>
                      </tr>
                      <tr>
                        <td>Time:</td>
                        <td><%= @game.time %></td>
                      </tr>
                    </tbody>
                  </table>
                  <br>
                  <br>
                  <%= link_to 'Back', :back, class: 'btn btn-primary fa fa-back' %>
                </div>
            </div>
          </div>
        </section><!-- /.Left col -->
      </div><!-- /.row (main row) -->
    </section><!-- /.content -->
  </aside><!-- /.right-side -->
</div><!-- ./wrapper -->